services:
  frontend:
    container_name: container_frontend
    build: 
     context: .
     target: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./env/development.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXT_WEBPACK_ENABLED=1
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - API_URL_INTERNAL=${API_URL_INTERNAL}
    stdin_open: true
    tty: true
    networks:
      - network_connect

networks:
  network_connect:
    external: true
